const RETRIEVE_BASKET = 'RETRIEVE_BASKET';
const REQUEST_SUBMIT_ORDER = 'REQUEST_SUBMIT_ORDER';
const RECEIVE_SUBMIT_ORDER = 'RECEIVE_SUBMIT_ORDER';
export default {
  RETRIEVE_BASKET,
  REQUEST_SUBMIT_ORDER,
  RECEIVE_SUBMIT_ORDER
  ,
}
