
const ADD_RECIPE_TO_BASKET = 'ADD_RECIPE_TO_BASKET';
const REQUEST_RECIPE_BY_ID = 'REQUEST_RECIPE_BY_ID';
const RECEIVE_RECIPE_BY_ID = 'RECEIVE_RECIPE_BY_ID';
const TOUCH = '@@redux-form/TOUCH';
const SET_SUBMIT_SUCCEEDED = '@@redux-form/SET_SUBMIT_SUCCEEDED';
export default {
    ADD_RECIPE_TO_BASKET,
    REQUEST_RECIPE_BY_ID,
    RECEIVE_RECIPE_BY_ID,
    TOUCH,
    SET_SUBMIT_SUCCEEDED

}
