
const ADD_RECIPE_TO_BASKET = 'ADD_RECIPE_TO_BASKET';
const REQUEST_RECIPE_BY_ID = 'REQUEST_RECIPE_BY_ID';
const RECEIVE_RECIPE_BY_ID = 'RECEIVE_RECIPE_BY_ID';
const REQUEST_IMAGE_BY_ID = 'REQUEST_IMAGE_BY_ID';
const RECEIVE_IMAGE_BY_ID = 'RECEIVE_IMAGE_BY_ID';
export default {
    ADD_RECIPE_TO_BASKET,
    REQUEST_RECIPE_BY_ID,
    RECEIVE_RECIPE_BY_ID,
    REQUEST_IMAGE_BY_ID,
    RECEIVE_IMAGE_BY_ID

}
