
const REQUEST_RECIPE_ID = 'REQUEST_RECIPE_ID';
const RECEIVE_RECIPE_ID = 'RECEIVE_RECIPE_ID';
const RELOAD_PAGE = 'RELOAD_PAGE';

export default {
    REQUEST_RECIPE_ID,
    RECEIVE_RECIPE_ID,
    RELOAD_PAGE
}
