const REQUEST_RECIPE_ID = 'REQUEST_RECIPE_ID';
const RECEIVE_RECIPE_ID = 'RECEIVE_RECIPE_ID';
const FETCH_RECIPES = 'FETCH_RECIPES';

export default {
    FETCH_RECIPES,
    REQUEST_RECIPE_ID,
    RECEIVE_RECIPE_ID
}
